version: '3.9'
services:
  zomink-server:
    restart: always
    container_name: zomink-server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build:
      context: ./
    image: zomink-server
    ports:
      - 8000:8000
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/server/Caddyfile:/root/zomink-server/server/Caddyfile
      - $PWD/server/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
